name: Profile Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coding-habits:
    runs-on: ubuntu-latest

    steps:
      - name: Generate coding habits
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""

          config_timezone: Asia/Shanghai

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14

          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: yes

          plugin_habits_languages_limit: 0
